### ISSUE TITLE
[Security]: Vulnerable to `Challenge Collapsar`

### ISSUE THREAD

**Issue by BlackHole1** [SkeLLLa/fastify-metrics#41]
The current plugin has enableRouteMetrics turned on by default

fastify-metrics will record all http requests and put them in memory
when the server suffers a `Challenge Collapsar Attack` , the data in memory will grow and never be cleared
because grafana gets statistics every once in a while, the entire nodejs process is blocked
eventually, the server becomes unavailable

<img width="2182" alt="图片" src="https://user-images.githubusercontent.com/8198408/136546061-cf405e70-d2df-4633-b005-9acbec5c0cce.png">

<img width="812" alt="图片" src="https://user-images.githubusercontent.com/8198408/136545755-fad1075d-cf96-4f05-9a9d-ab21547d1af1.png">

<img width="2059" alt="图片" src="https://user-images.githubusercontent.com/8198408/136546229-b35bb451-caf6-489b-94cb-d52de9d17827.png">

<img width="717" alt="图片" src="https://user-images.githubusercontent.com/8198408/136546586-4c1828b9-9e0f-44ce-b1a6-0a8189fd3bdb.png">

---

You can use https://github.com/projectdiscovery/nuclei to perform simulation tests (`./nuclei -u domain`)
This tool will make 150 requests per second, with 10 concurrent

**Comment by Givemeurcookies** [comment]
> grafana gets statistics every once in a while, the entire nodejs process is blocked eventually, the server becomes unavailable

Good catch! I am not the maintainer of the project but the quoted line is a bit confusing. I think I understood what you meant, but it's probably better to clarify it a bit.

From what I understood from the report and after testing this project a bit, I can certainly see there's a security flaw; Grafana Prometheus scrapes the metrics endpoint on set intervals but this doesn't clear the Node process metrics. So a malicious user could technically send a lot of requests to the Fastify server with different invalid endpoints. Those invalid endpoints will then be recorded in the metrics overview but is never cleared.

When Prometheus then scrapes the metrics endpoint, it will gradually require more and more I/O due to having to scrape the ever so increasing list of metrics + when Prometheus is using all that I/O the server will eventually become unresponsive. By this logic I also believe that with enough invalid endpoint the process will eventually run out of memory and crash on its own.

If that covers the security flaw, I think the temporary solution is to set the option: `invalidRouteGroup:true` (@SkeLLLa maybe make this default?) then this security flaw should be mitigated. It doesn't makes much sense to put metrics on every invalid route either way, I believe that's traditionally done through logging and log aggregation. I.e you could use Grafana Loki to log invalid requests and aggregate through those if you wish to get metrics for invalid routes. That way you don't need to store the metrics in memory or on the service.

**Comment by SkeLLLa** [comment]
Yes, invalidRouteGroup was designed for this purpose. 

However in v9 I've redefined config and removed possibility to log all queries at all. Now it collects metrics only for registered routes. And via flag it it possible to collect unknown route metrics as well.
